#!perl
use Cassandane::Tiny;

sub test_calendarevent_set_defaultalerts_caldav_acknowledged
    :min_version_3_7 :needs_component_jmap
{
    my ($self) = @_;

    my $jmap = $self->{jmap};
    my $caldav = $self->{caldav};

    my $defaultAlarmUid = 'f85ce9b2-c4c5-4b9e-b017-3dd82b559626';
    my $unacknowledgedAlarmUid = '23bd9d3f-e8f3-4ad1-a768-48bb26e5f8d1';
    my $acknowledgedAlarmUid = '1a484393-c55d-4d04-9467-312c1b49074d';
    my $relatedAlarmUid = '05d1a162-b1c3-4b6c-b99c-15568d8afbb3';

    xlog "Update default alerts on calendar";
    $res = $jmap->CallMethods([
        ['Calendar/set', {
            update => {
                Default => {
                    defaultAlertsWithTime => {
                        alert1 => {
                            '@type' => 'Alert',
                            uid => $defaultAlarmUid,
                            trigger => {
                                '@type' => 'OffsetTrigger',
                                relativeTo => 'start',
                                offset => '-PT5M',
                            },
                            action => 'display',
                        },
                    },
                }
            }
        }, 'R1'],
    ]);
    $self->assert(exists $res->[0][1]{updated}{Default});


    xlog "PUT event with acknowledged/snoozed alarms";
    my $ical = <<"EOF";
BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//Apple Inc.//Mac OS X 10.9.5//EN
CALSCALE:GREGORIAN
BEGIN:VEVENT
TRANSP:TRANSPARENT
DTSTART;TZID=Europe/Vienna:20160928T160000
DTEND;TZID=Europe/Vienna:20160928T170000
UID:72a66940-3694-48a8-b332-0de9fb73016d
DTSTAMP:20150928T132434Z
CREATED:20150928T125212Z
SUMMARY:test
LAST-MODIFIED:20150928T132434Z
X-JMAP-USEDEFAULTALERTS:TRUE
BEGIN:VALARM
UID:$unacknowledgedAlarmUid
TRIGGER:-PT5M
ACTION:DISPLAY
END:VALARM
BEGIN:VALARM
UID:$acknowledgedAlarmUid
ACTION:DISPLAY
TRIGGER;VALUE=DATE-TIME:20160928T135500Z
ACKNOWLEDGED:20160928T140005Z
END:VALARM
BEGIN:VALARM
UID:$relatedAlarmUid
ACTION:DISPLAY
RELATED-TO:$acknowledgedAlarmUid
TRIGGER;VALUE=DATE-TIME:20160928T150005Z
END:VALARM
END:VEVENT
END:VCALENDAR
EOF
    $caldav->Request('PUT', 'Default/test.ics', $ical,
        'Content-Type' => 'text/calendar');

    my $res = $caldav->Request('GET', 'Default/test.ics');

    xlog "Assert acknowledged VALARM is kept";
    $self->assert($res->{content} =~ $acknowledgedAlarmUid);
    $self->assert($res->{content} =~ 'ACKNOWLEDGED:20160928T140005Z');

    xlog "Assert related VALARM is kept";
    $self->assert($res->{content} =~ $relatedAlarmUid);

    xlog "Assert unacknowledged VALARM is removed";
    $self->assert(not $res->{content} =~ $unacknowledgedAlarmUid);

    xlog "Assert default VALARM is set";
    $self->assert($res->{content} =~ $defaultAlarmUid);
}
