#!perl
use Cassandane::Tiny;

sub test_xxx
  : needs_component_jmap : JMAPExtensions : needs_component_sieve {
    my ($self) = @_;
    my $jmap   = $self->{jmap};
    my $imap   = $self->{store}->get_client();

    $jmap->AddUsing('https://cyrusimap.org/ns/jmap/debug');
    $jmap->AddUsing('https://cyrusimap.org/ns/jmap/performance');

    my $mime = <<'EOF';
From: from@local
To: to@local
Message-ID: <Foo@EXAMPLE.com>
Subject: test
Date: Mon, 13 Apr 2020 15:34:03 +0200
MIME-Version: 1.0
Content-Type: multipart/alternative;
 boundary=04520009ed384fc2a27689294619e15e

--04520009ed384fc2a27689294619e15e
Content-Type: text/plain; charset=utf-8
Content-Transfer-Encoding: quoted-printable

=F0=9F=A4=A6 oh no!
--04520009ed384fc2a27689294619e15e
Content-Type: text/html
Content-Transfer-Encoding: 8bit

<!DOCTYPE html><html><head><title></title></head><body><div>🤦 oh no!<br></div></body></html>
--04520009ed384fc2a27689294619e15e
Content-Type: text/html
Content-Transfer-Encoding: quoted-printable

<!DOCTYPE html><html><head><title></title></head><body><div>=F0=9F=A4=A6 oh=
 no!<br></div></body></html>
--04520009ed384fc2a27689294619e15e--

test
EOF
    $mime =~ s/\r?\n/\r\n/gs;
    $imap->append('INBOX', $mime) || die $@;

    xlog $self, "run squatter";
    $self->{instance}->run_command({ cyrus => 1 }, 'squatter');

    my $res = $jmap->CallMethods([
        [ 'Email/query', {}, 'R1' ],
        [
            'Email/get',
            {
                '#ids' => {
                    resultOf => 'R1',
                    path     => '/ids',
                    name     => 'Email/query',
                },
                fetchAllBodyValues => JSON::true,
                properties => ['preview', 'bodyValues'],
            },
            'R2'
        ]
    ]);

    $self->assert_matches(qr/\N{FACE PALM} oh no!/, $res->[1][1]{list}[0]{preview});
    $self->assert_matches(qr/\N{FACE PALM} oh no!/, $res->[1][1]{list}[0]{bodyValues}{1}{value});
    $self->assert_matches(qr/\N{FACE PALM} oh no!/, $res->[1][1]{list}[0]{bodyValues}{2}{value});
    $self->assert_matches(qr/\N{FACE PALM} oh no!/, $res->[1][1]{list}[0]{bodyValues}{3}{value});
}
